import os
import re
import json
import math
from groq import Groq
from dotenv import load_dotenv

load_dotenv()

_client = Groq(api_key=os.environ.get("GROQ_API_KEY"))

PROMPT_TEMPLATE = """You are an expert at distinguishing between human-written and AI-generated text.

Analyze the text below and assess whether it was written by a human or generated by AI.

Consider:
- Sentence structure variety and unpredictability
- Vocabulary diversity and naturalness
- Presence of personal voice, emotion, or idiosyncrasies
- Statistical uniformity (AI text tends to be more consistent and polished)

Respond ONLY with a JSON object in this exact format:
{{"ai_probability": <float between 0.0 and 1.0>, "reasoning": "<one sentence explanation>"}}

Where ai_probability is:
- Close to 1.0 if the text strongly appears AI-generated
- Close to 0.0 if the text strongly appears human-written
- Around 0.5 if you are uncertain

Text to analyze:
\"\"\"
{text}
\"\"\"

JSON only. No other text."""


def classify_with_llm(text: str) -> dict:
    response = _client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[{"role": "user", "content": PROMPT_TEMPLATE.format(text=text)}],
        temperature=0.1,
        max_tokens=200,
    )

    raw = response.choices[0].message.content.strip()

    try:
        result = json.loads(raw)
        return {
            "ai_probability": float(result["ai_probability"]),
            "reasoning": result.get("reasoning", ""),
        }
    except (json.JSONDecodeError, KeyError, ValueError):
        return {"ai_probability": 0.5, "reasoning": "Could not parse model response."}


def compute_stylometric_score(text: str) -> float:
    """
    Returns a 0-1 score where higher = more AI-like.
    Combines two metrics:
      - Sentence length variance (low variance = AI-like)
      - Type-token ratio (low vocabulary diversity = AI-like)
    """
    words = re.findall(r"\b\w+\b", text.lower())
    sentences = [s.strip() for s in re.split(r"[.!?]+", text) if s.strip()]

    if not words or not sentences:
        return 0.5

    # Metric 1: sentence length variance
    # AI text has uniform sentence lengths → low std dev → high AI score
    lengths = [len(re.findall(r"\b\w+\b", s)) for s in sentences]
    if len(lengths) > 1:
        mean = sum(lengths) / len(lengths)
        std_dev = math.sqrt(sum((l - mean) ** 2 for l in lengths) / len(lengths))
    else:
        std_dev = 0.0
    # std_dev of 0 → score 1.0 (AI-like); std_dev >= 10 → score 0.0 (human-like)
    variance_score = max(0.0, 1.0 - (std_dev / 10.0))

    # Metric 2: type-token ratio (vocabulary diversity)
    # High TTR → human; Low TTR → AI
    ttr = len(set(words)) / len(words)
    ttr_score = 1.0 - ttr  # invert: low diversity = high AI score

    style_score = (0.5 * variance_score) + (0.5 * ttr_score)
    return round(min(1.0, max(0.0, style_score)), 4)


def compute_confidence(llm_score: float, style_score: float) -> dict:
    """
    Combines both signals into a single confidence score.
    LLM carries 60% weight; stylometric carries 40%.
    Thresholds: >= 0.70 → likely_ai, 0.35–0.70 → uncertain, < 0.35 → likely_human
    """
    combined = round((0.6 * llm_score) + (0.4 * style_score), 4)

    if combined >= 0.70:
        attribution = "likely_ai"
    elif combined >= 0.35:
        attribution = "uncertain"
    else:
        attribution = "likely_human"

    return {"score": combined, "attribution": attribution}


if __name__ == "__main__":
    samples = [
        (
            "clearly AI",
            "Artificial intelligence represents a transformative paradigm shift in modern society. "
            "It is important to note that while the benefits of AI are numerous, it is equally "
            "essential to consider the ethical implications. Furthermore, stakeholders across "
            "various sectors must collaborate to ensure responsible deployment."
        ),
        (
            "clearly human",
            "ok so i finally tried that new ramen place downtown and honestly? "
            "underwhelming. the broth was fine but they put WAY too much sodium in it and "
            "i was thirsty for like three hours after. my friend got the spicy version and "
            "said it was better. probably won't go back unless someone drags me there"
        ),
        (
            "borderline — formal human writing",
            "The relationship between monetary policy and asset price inflation has been "
            "extensively studied in the literature. Central banks face a fundamental tension "
            "between their mandate for price stability and the unintended consequences of "
            "prolonged low interest rates on equity and real estate valuations."
        ),
        (
            "borderline — lightly edited AI",
            "I've been thinking a lot about remote work lately. There are genuine tradeoffs — "
            "flexibility and no commute on one side, isolation and blurred work-life boundaries "
            "on the other. Studies show productivity varies widely by individual and role type."
        ),
    ]

    print(f"{'Label':<35} {'llm':>5} {'style':>6} {'combined':>9} {'attribution'}")
    print("-" * 70)
    for label, text in samples:
        llm = classify_with_llm(text)["ai_probability"]
        style = compute_stylometric_score(text)
        result = compute_confidence(llm, style)
        print(f"{label:<35} {llm:>5.2f} {style:>6.4f} {result['score']:>9.4f}  {result['attribution']}")
